#!/bin/bash

echo "Running git pre-commit hook..."

echo "Building app..."
./gradlew bootJar

# For building in the host
# echo "Building docker image..."
# docker build --target base --tag wtc-image .
# docker run --rm -v "$(pwd)":/var/app wtc-image ./gradlew bootJar

RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "Build verifications failed. Check the changes and try again"
  exit 1
fi

exit 0
